server:
  port: 7777

spring:
  application:
    name: auth
  security:
    oauth2:
      authorizationserver:
        issuer-url: http://localhost:7777
      client:
        registration:
          google:
            clientId: 913281890805-doap1sec6btmsnp0pvrq12a11cd3emae.apps.googleusercontent.com
            clientSecret: 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
